apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: azure-vote-back
  newName: app-azure-vote-app
  newTag: merge-6a6e7238bc291132dbab71dec0941b61c2f4619d
