apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../services/$SERVICE_NAME
patchesStrategicMerge:
 - $SERVICE_NAME-virtual-service.yaml
 - $SERVICE_NAME-image.yaml